import type { Teacher } from "~/types/schedule/Teacher";
import { grades } from "~/utils/grades";

export const teachers: Teacher[] = [
	{
		id: 0,
		firstName: "Игорь",
		lastName: "Куянов",
		middleName: "Александрович",
		grade: grades.professor,
		image: "",
	},
	{
		id: 1,
		firstName: "Татьяна",
		lastName: "Слободинская",
		middleName: "Васильевна",
		grade: grades.boss,
		image: "",
	},
	{
		id: 2,
		firstName: "Павел",
		lastName: "Фарберов",
		middleName: "Яковлевич",
		grade: grades.highTeacher,
		image: "",
	},
	{
		id: 3,
		firstName: "Алексей",
		lastName: "Федин",
		middleName: "Константинович",
		email: "LabsandEverything@gmail.com",
		grade: grades.highTeacher,
		image: "",
	},
	{
		id: 4,
		firstName: "Наталья",
		lastName: "Гуськова",
		middleName: "Владимировна",
		grade: grades.highTeacher,
		image: "",
	},
	{
		id: 5,
		firstName: "Иван",
		lastName: "Корниенко",
		middleName: "Григорьевич",
		email: "LabsandEverything@gmail.com",
		grade: grades.assistantProfessor,
		image: "",
	},
	{
		id: 6,
		firstName: "Андрей",
		lastName: "Gayков",
		middleName: "Владимирович",
		grade: grades.assistantProfessor,
		image: "",
	},
	{
		id: 7,
		firstName: "Татьяна",
		lastName: "Винник",
		middleName: "Викторовна",
		grade: grades.assistantProfessor,
		image: "",
	},
	{
		id: 8,
		firstName: "кафедры",
		lastName: "Преподаватели",
		middleName: "физкультуры",
		grade: grades.highTeacher,
		image: "",
	},
	{
		id: 9,
		firstName: "Александра",
		lastName: "Пономарева",
		middleName: "Александровна",
		grade: grades.highTeacher,
		image: "",
	},
	{
		id: 10,
		firstName: "Ирина",
		lastName: "Потехина",
		middleName: "Павловна",
		grade: grades.assistantProfessor,
		image: "",
	},
	{
		id: 11,
		firstName: "Петр",
		lastName: "Гостенков",
		middleName: "Анатольевич",
		grade: grades.highTeacher,
		image: "",
	},
	{
		id: 12,
		firstName: "Мария",
		lastName: "Клюс",
		middleName: "Владимировна",
		grade: grades.highTeacher,
		image: "",
	},
	{
		id: 13,
		firstName: "Светлана",
		lastName: "Миронова",
		middleName: "Борисовна",
		grade: grades.highTeacher,
		image: "",
	},
	{
		id: 14,
		firstName: "Светлана",
		lastName: "Хотунцова",
		middleName: "Владимировна",
		grade: grades.assistantProfessor,
		image: "",
	},
	{
		id: 15,
		firstName: "Анатолий",
		lastName: "Волков",
		middleName: "Андреевич",
		grade: grades.assistantProfessor,
		image: "",
	},
	{
		id: 16,
		lastName: "Ананченко",
		firstName: "Игорь",
		middleName: "Викторович",
		grade: grades.assistantProfessor,
	},
	{
		id: 17,
		lastName: "Гонашвили",
		firstName: "Александр",
		middleName: "Сергеевич",
		grade: grades.highTeacher,
	},
	{
		id: 18,
		lastName: "Халимон",
		firstName: "Виктория",
		middleName: "Ивановна",
		grade: grades.professor,
	},
	{
		id: 19,
		lastName: "Груздков",
		firstName: "Алексей",
		middleName: "Андреевич",
		grade: grades.professor,
	},
	{
		id: 20,
		lastName: "Ремизова",
		firstName: "Ольга",
		middleName: "Васильевна",
		grade: grades.assistantProfessor,
	},
	{
		id: 21,
		lastName: "Проститенко",
		firstName: "Олег",
		middleName: "Владимирович",
		grade: grades.assistantProfessor,
	},
	{
		id: 22,
		lastName: "Штеренберг",
		firstName: "Игорь",
		middleName: "Григорьевич",
		grade: grades.assistantProfessor,
	},
	{
		id: 23,
		lastName: "Хрусталев",
		firstName: "Андрей",
		middleName: "Михайлович",
		grade: grades.highTeacher,
	},
	{
		id: 24,
		lastName: "Макарук",
		firstName: "Роман",
		middleName: "Валерьевич",
		grade: grades.assistantProfessor,
	},
	{
		id: 25,
		lastName: "Иванов",
		firstName: "Александр",
		middleName: "Александрович",
		grade: grades.highTeacher,
	},
	{
		id: 26,
		lastName: "Кузнецова",
		firstName: "Галина",
		middleName: "Викторовна",
		grade: grades.assistantProfessor,
	},
	{
		id: 27,
		lastName: "Дамрин",
		firstName: "Антон",
		middleName: "Телеговский",
		grade: grades.highTeacher,
		email: "@damrin_toni",
	},
	{
		id: 28,
		lastName: "Смирнов",
		firstName: "Алексей",
		middleName: "Юрьевич",
		grade: grades.highTeacher,
	},
	{
		id: 29,
		lastName: "Соболевский",
		firstName: "Владислав",
		middleName: "Алексеевич",
		grade: grades.highTeacher,
	},
	{
		id: 30,
		lastName: "Шашкина",
		firstName: "Антонина",
		middleName: "Сергеевна",
		grade: grades.labAssistant,
	},
	{
		id: 31,
		lastName: "Свечников",
		firstName: "Андрей",
		middleName: "Анатольевич",
		grade: grades.assistantProfessor,
	},
	{
		id: 32,
		lastName: "Шиманская",
		firstName: "Галина",
		middleName: "Станиславовна",
		grade: grades.labAssistant,
	},
	{
		id: 33,
		lastName: "Коряжкина",
		firstName: "Оксана",
		middleName: "Витальевна",
		grade: grades.highTeacher,
	},
	{
		id: 34,
		lastName: "Дьяченко",
		firstName: "Semen",
		middleName: "Андреевич",
		grade: grades.labAssistant,
	},
];
